version: "3"

services:
  web:
    build:
      context: build/docker
      dockerfile: Dockerfile.local
    environment: 
      ENVIRONMENT: Prod
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config:ro
      - ./dist:/app/dist:ro