################################ rust-musl-builder
FROM ekidd/rust-musl-builder:latest AS builder

ADD --chown=rust:rust . ./

RUN cargo build --release

################################ actual prod image
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/portfolio .

CMD /app/portfolio