name: CI
on:
  push:
    branches-ignore:
    - 'master'
    paths:
    - 'src/**.rs'

jobs:
  build_and_test:
    name: build rust backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features